<?php

use Drupal\Core\Url;

function corillabase_mod_preprocess(&$variables) {
  
  global $base_url;
  
  // Recupero il tema attivo.
  $active_theme = \Drupal::theme()->getActiveTheme();
  $active_theme_name = $active_theme->getName();
  $active_theme_path = $active_theme->getPath();
  
  // Creo la viariabile contenente il logo del tema.
  $active_theme_logo = file_get_contents(drupal_get_path('theme', $active_theme_name) . '/logo.svg');
  $variables['active_theme_logo'] = $active_theme_logo;

  // Creo la variabile contenente il path assoluto al tema.
  $variables['active_theme_path'] = $base_url . '/' . $active_theme_path;
  
}

function corillabase_mod_preprocess_html(&$variables) {
  
  // Aggiungo l'id del nodo alle classi del body.
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node) {
    $variables['attributes']['class'][] = 'page-node-' . $node->id();
  }

  // Aggiungo i tipi di utente dell'utente attuale alle classi del body.
  $user_roles = \Drupal::currentUser()->getRoles();
  if ($user_roles) {
    foreach ($user_roles as $user_role) {
      $variables['attributes']['class'][] = 'user-type-' . $user_role;
    }
  }
  
}

function corillabase_mod_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  
  // Imposto il testo dell'elemento 'Privacy policy' dei form.
  $privacy_policy_node = 2;
  $privacy_policy_link = Url::fromRoute('entity.node.canonical', ['node' => $privacy_policy_node], ['absolute' => TRUE])->toString();
  $privacy_policy_text = 'Dichiaro di aver letto e accettato la <a target="_blank" href=' . $privacy_policy_link . '>privacy policy</a> in ogni sua parte.';
  if (isset($form['elements']['privacy'])) {
    $form['elements']['privacy']['#title'] = $privacy_policy_text;
    $form['elements']['privacy']['#description']['#markup'] = '';
  }
  if (isset($form['field_privacy'])) {
    $form['field_privacy']['widget']['value']['#title'] = $privacy_policy_text;
  }

}