echo "Inizializzazione repository Git..."

# Aggiungo contenuto al file .gitignore.
gitignore_append="
# Ignore directories generated by Composer
/vendor/
/web/core/
/web/modules/contrib/
/web/themes/contrib/
/web/profiles/contrib/
/web/libraries/*

!/web/libraries/blazy/
!/web/libraries/slick/

# Ignore sensitive information
/web/sites/*/settings.php
/web/sites/*/settings.local.php

# Ignore Drupal's file directory
/web/sites/*/files/

# Ignore SimpleTest multi-site environment.
/web/sites/simpletest

# Ignore files generated by PhpStorm
/.idea/

# Ignore .env files as they are personal
/.env

# Extra

/web/sites/default/settings.php

/private/
/tmp/

/composer-setup.php
/composer.phar

.sass-cache
.netbeans.xml
nbproject/
node_modules/

#Librerie
!/web/libraries/blazy/
!/web/libraries/slick/

# Cache
/config/sync/system.performance.yml
/config/sync/advagg.settings.yml
/config/sync/minifyhtml.config.yml

# Backup and Migrate
/config/sync/backup_migrate.backup_migrate_schedule.*
"

touch "${htmlPath}"/.gitignore
sed -i "s/web\/libraries\//web\/libraries\/*/g" "${htmlPath}"/.gitignore
echo -e "$gitignore_append" >> "${htmlPath}"/.gitignore

# Inizializzo la repository Git. Commentata perchè superflua secondo me
# git init "${htmlPath}"

echo "Repository Git inizializzata in "${htmlPath}"."